# Generated by Django 2.2 on 2020-06-10 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='Cart/ProfileImage')),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateTimeField(auto_now=True)),
                ('usr_type', models.IntegerField(choices=[(1, 'Admin'), (2, 'User')], default=2)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
