# Generated by Django 2.2 on 2020-06-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_userprofile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='Cart/productImage')),
                ('productCoast', models.IntegerField()),
                ('productCoas', models.FloatField()),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
