# Generated by Django 2.2 on 2020-06-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productCoas',
        ),
        migrations.AlterField(
            model_name='product',
            name='productCoast',
            field=models.FloatField(),
        ),
    ]
