# Generated by Django 2.2 on 2020-06-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_auto_20200610_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productDesc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
