# Generated by Django 2.2 on 2020-06-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checkOut',
            field=models.BooleanField(default=False),
        ),
    ]
