# Generated by Django 2.2 on 2020-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_cart_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productCoast',
            field=models.FloatField(default=0),
        ),
    ]
