# Generated by Django 2.2 on 2020-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_cart_productcoast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productCoast',
            field=models.FloatField(),
        ),
    ]
