# Generated by Django 2.2 on 2020-06-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0010_auto_20200611_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=False, max_length=10)),
                ('discount', models.FloatField(default=False)),
            ],
            options={
                'db_table': 'Coupon',
            },
        ),
    ]
